# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d053b820b0620ddd03f020135bf3cf94dc38034d87b87a015d1329bacb8c22175c856e3744a0dd36142517fb31e16e2dded25bdf27ec63e5e2dc25024bc1be2

test:
  secret_key_base: c57078c2099cd9b53054d74a59d36ab76c969ef5b0d28fef74a1549723b00f7bdbf8ace9b266d92773a283ef381f22e0376392d8e4141543673059013203d68d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
